name: 'rancher'

services:
  rancher:
    image: rancher/rancher:v2.11.1
    container_name: rancher
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./rancher_data:/var/lib/rancher
      - ./rancher_certs/cert.pem:/etc/rancher/ssl/cert.pem
      - ./rancher_certs/key.pem:/etc/rancher/ssl/key.pem
    command:
      - --https-listen-port
      - "443"
      - --no-cacerts
    privileged: true
    networks:
      - rancher

networks:
  rancher:
    driver: bridge

    