name: 'rancher'

services:
  rancher:
    image: rancher/rancher:v2.11.1
    container_name: rancher
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - rancher_data:/var/lib/rancher
    # environment:
    #   - CATTLE_BOOTSTRAP_PASSWORD=admin
    privileged: true

volumes:
  rancher_data: