version: '3.8'

services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    restart: unless-stopped
    ports:
      - "10080:80"
      - "10443:443"
    volumes:
      - rancher-data:/var/lib/rancher
    # environment:
    #   - CATTLE_BOOTSTRAP_PASSWORD=admin
    privileged: true

volumes:
  rancher-data: