name: 'mysql'

services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password} # Fallback to 'rootpassword' if not set
      MYSQL_DATABASE: ${MYSQL_DATABASE:-springboot} # Fallback to 'mydatabase' if not set
      MYSQL_USER: ${MYSQL_USER:-admin} # Fallback to 'myuser' if not set
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password} # Fallback to 'mypassword' if not set
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network


volumes:
  mysql_data:

networks:
  mysql_network:
    driver: bridge