apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs-redis-pv
spec: 
  capacity: 
    storage: 10Gi
  accessModes: 
  - ReadWriteMany
  nfs: 
    path: /data/redis
    server: 192.111.33.102
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: nfs-redis-pvc
  namespace: architecture
spec: 
  accessModes: 
  - ReadWriteMany
  resources: 
    requests: 
      storage: 10Gi
  storageClassName: nfs-storage
