architecture: replication

auth:
  enabled: true
  password: "devopseduvn"

master:
  persistence:
    enabled: true
    existingClaim: nfs-redis-pvc
    size: 3Gi

replica:
  replicaCount: 2
  persistence:
    enabled: true
    existingClaim: nfs-redis-pvc
    size: 3Gi

sentinel:
  enabled: true
  replicas: 2