apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: the-school
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: theschool.dev
  apiGroup: rbac.authorization.k8s.ios
