apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-mysql
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    path: /nfs/share/mysql
    server: 192.168.1.37
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-mysql
  namespace: ecommerce
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-storage
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ecommerce
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQK # password
  MYSQL_DATABASE: ZWNvbW1lcmNlCg== # ecommerce
  MYSQL_USER: ZWNvbW1lcmNlCg== # ecommerce
  MYSQL_PASSWORD: cGFzc3dvcmQK # password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  namespace: ecommerce
spec:
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      securityContext:
        fsGroup: 65534
      containers:
      - name: mysql-server
        image: mysql:8.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: mysql-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: nfs-pvc-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-server-service
  namespace: ecommerce
spec:
  selector:
    app: mysql-server
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-port
  type: LoadBalancer
