Vagrant.configure("2") do |config|

  # Prometheus VM
  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.hostname = "master"
    master.vm.network "public_network",
      ip: "192.168.1.201",
      bridge: "wlp2s0"

    master.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu-master"
      vb.memory = "2048"
      vb.cpus = 1
    end

    master.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get upgrade -y
    SHELL
  end

  # Dev VM
  config.vm.define "worker1" do |worker1|
    worker1.vm.box = "ubuntu/jammy64"
    worker1.vm.hostname = "worker1"
    worker1.vm.network "public_network",
      ip: "192.168.1.202",   # ← Different IP!
      bridge: "wlp2s0"

    worker1.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu-worker1"
      vb.memory = "2048"
      vb.cpus = 1
    end

    worker1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get upgrade -y
    SHELL
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.box = "ubuntu/jammy64"
    worker2.vm.hostname = "worker2"
    worker2.vm.network "public_network",
      ip: "192.168.1.203",
      bridge: "wlp2s0"

    worker2.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu-worker2"
      vb.memory = "2048"
      vb.cpus = 1
    end

    # grafana.vm.provision "shell", inline: <<-SHELL
    #   sudo apt-get update
    #   sudo apt-get install -y apt-transport-https software-properties-common wget
    #   wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
    #   echo "deb https://packages.grafana.com/oss/deb stable main" | sudo tee /etc/apt/sources.list.d/grafana.list
    #   sudo apt-get update
    #   sudo apt-get install -y grafana
    #   sudo systemctl enable grafana-server
    #   sudo systemctl start grafana-server
    # SHELL
  end

end
