# Vagrantfile for Kubernetes cluster with 1 master and 2 workers
Vagrant.configure("2") do |config|
  NODES = [
    { name: "master",  ip: "192.168.56.201" },
    { name: "worker1", ip: "192.168.56.202" },
    { name: "worker2", ip: "192.168.56.203" }
  ]

  NODES.each do |node|
    config.vm.define node[:name] do |vm|
      vm.vm.box = "ubuntu/jammy64"
      vm.vm.hostname = node[:name]
      vm.vm.network "private_network", ip: node[:ip]

      vm.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-#{node[:name]}"
        vb.memory = 2048
        vb.cpus = 2
      end

      vm.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y python3 python3-pip
      SHELL
    end
  end
end

