apiVersion: v1
kind: Pod
metadata:
  name: nfs-nginx
  namespace: ecommerce
  labels:
    name: nfs-nginx
spec:
  containers:
  - name: nfs-nginx
    image: nginx  
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nfs-storage
    ports:
      - containerPort: 80
  volumes:
  - name: nfs-storage
    persistentVolumeClaim:
      claimName: nfs-pvc
