global:
  # the smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'example@gmail.com'
  # SMTP authentication credentials
  smtp_auth_username: 'example@gmail.com'
  smtp_auth_password: 'password'
#  smtp_require_tls: false
route:
  receiver: 'email'
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  # routes:
  # - receiver: 'urgent_receiver'
  #   matchers:
  #     - severity="Critical"

receivers:
  - name: 'email'
    email_configs:
      - to: 'example@gmail.com'
        send_resolved: true

  - name: 'urgent_receiver'
    email_configs:
      - to: 'example@gmail.com'