global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'file_sd'
    file_sd_configs:
      - files:
          - files_sd/*.yml
        refresh_interval: 10s

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'shoehub'
    static_configs:
      - targets: ['shoehub:8080']

rule_files:
  - './rules/alerts.yml'
  - './rules/record-rule.yml'
