all:
  hosts:
    k8s_master:
      ansible_host: 192.168.1.201
      ansible_user: hieunv
    worker1:
      ansible_host: 192.168.1.202
      ansible_user: hieunv
    worker2:
      ansible_host: 192.168.1.203
      ansible_user: hieunv
  children:
    k8s_master:
      hosts:
        k8s_master: {}
    k8s_workers:
      hosts:
        worker1: {}
        worker2: {}
