all:
  hosts:
    k8s_master:
      ansible_host: 192.111.33.201
      ansible_user: vagrant
    worker1:
      ansible_host: 192.111.33.202
      ansible_user: vagrant
    worker2:
      ansible_host: 192.111.33.203
      ansible_user: vagrant
  children:
    k8s_master:
      hosts:
        k8s_master: {}
    k8s_workers:
      hosts:
        worker1: {}
        worker2: {}
