apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
  name: ecommerce-backend-hpa
  namespace: ecommerce
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: ecommerce-backend
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50