apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-backend-database-connection
  namespace: ecommerce
type: Opaque
stringData:
  MYSQL_HOST: "192.111.33.113"
  MYSQL_PORT: "3306"
  MYSQL_DB: "full-stack-ecommerce"
  MYSQL_USERNAME: "ecommerceapp"
  MYSQL_PASSWORD: "StrongPa55WorD"
  
