{
 "title": "ShoeHub",
 "time": { "from": "2025-05-30T00:05:17.249Z", "to": "2025-05-30T00:11:09.181Z" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(shoehub_payments{PaymentMethod=\"Card\"}, CountryCode)"
    }
   },
   {
    "name": "paymentMethod",
    "label": "Payment Method",
    "query": {
     "query": "label_values(shoehub_payments, PaymentMethod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Payment Amount by $paymentMethod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "shoehub_payments{PaymentMethod=\"$paymentMethod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sale rating",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Boots\"}[1m])",
     "legendFormat": "Boots"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"HighHeels\"}[1m])",
     "legendFormat": "HighHeels"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[1m])",
     "legendFormat": "Loafers"
    }
   ]
  },
  {
   "title": "Sales Today vs. Sales Last Week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__rate_interval] offset 2m) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Card payments in Countries",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(shoehub_payments{CountryCode=\"AU\", PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "Australia"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"IN\", PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "India"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "US"
    }
   ]
  },
  {
   "title": "Sales Amount for $paymentMethod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "repeat": "paymentMethod",
   "targets": [
    {
     "expr": "shoehub_payments{PaymentMethod=\"$paymentMethod\"}",
     "legendFormat": "$paymentMethod amount"
    }
   ]
  },
  {
   "title": "Percentage of Payment Methods in the $country",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "repeat": "country",
   "targets": [
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Card\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Card"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Paypal\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Paypal"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Cash\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Cash"
    }
   ]
  }
 ]
}