apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-redis-pv
  namespace: architecture
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  mountOptions:
  - hard
  - nfsvers=4.1
  nfs:
    path: /nfs/share/redis
    server: 192.168.1.37
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-redis-pvc
  namespace: architecture
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-storage
---


